// Category icon key (utils/categoryIcons.js) → iconoir component. Shared by
// CategoryIcon (list rows) and CategoryIconPicker (category form).
import {
  Airplane,
  Car,
  Cart,
  CoffeeCup,
  Cutlery,
  Gamepad,
  Gift,
  GraduationCap,
  Gym,
  Heart,
  Home,
  Label,
  LightBulb,
  Phone,
  Shield,
  Shirt,
  ShoppingBag,
  Stroller,
} from "iconoir-react";

export const CATEGORY_ICON_COMPONENTS = {
  baby: Stroller,
  coffee: CoffeeCup,
  dining: Cutlery,
  groceries: Cart,
  household: ShoppingBag,
  utilities: LightBulb,
  phone: Phone,
  housing: Home,
  learning: GraduationCap,
  transport: Car,
  fitness: Gym,
  health: Heart,
  clothing: Shirt,
  entertainment: Gamepad,
  travel: Airplane,
  gift: Gift,
  insurance: Shield,
  other: Label,
  none: Label,
};
