import { describe, it, expect, vi } from 'vitest'
import { fireEvent, render, screen, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import ExpenseDayList, { ExpenseDayStrip, UpcomingExpenseList } from './ExpenseDayList'

const row = (id, occurredAt, amountTwd, extra = {}) => ({
  id,
  name: `支出${id}`,
  occurredAt,
  amountTwd,
  categoryName: '外食',
  payerName: 'Po',
  isRecurringOccurrence: false,
  isUpcoming: false,
  ...extra,
})

const rows = [
  row(1, '2026-10-04', 120, { name: '午餐' }),
  row(2, '2026-10-04', 80, { name: '咖啡', categoryName: '未指定', payerName: '未指定' }),
  row(3, '2026-10-02', 999, { name: '中華電信', categoryName: '家庭雜支', isRecurringOccurrence: true }),
  row(4, '2026-10-30', 1488, { name: 'World gym', categoryName: '健康', isRecurringOccurrence: true, isUpcoming: true }),
  row(5, '2026-10-20', 18000, { name: '房租', categoryName: '房屋', isRecurringOccurrence: true, isUpcoming: true }),
]

const renderList = (props = {}) => {
  const getActions = vi.fn((record) => [
    { key: 'edit', label: `編輯 ${record.name}`, text: '編輯', onClick: vi.fn() },
  ])
  render(
    <ExpenseDayList
      rows={rows}
      today="2026-10-04"
      getActions={getActions}
      empty={<div>沒有支出</div>}
      {...props}
    />,
  )
  return { user: userEvent.setup(), getActions }
}

describe('<ExpenseDayList />', () => {
  it('groups charged expenses by day with a subtotal, newest first', () => {
    renderList()
    const headings = screen.getAllByTestId('expense-day-heading').map((el) => el.textContent)
    expect(headings).toEqual(['今天 · 10/04（日）$200', '10/02（五）$999'])
  })

  it('shows category · payer under the name and skips unset values', () => {
    renderList()
    const lunch = screen.getByText('午餐').closest('.mobile-swipe-row')
    expect(lunch).toHaveTextContent('外食 · Po')
    expect(lunch).toHaveTextContent('$120')
    const coffee = screen.getByText('咖啡').closest('.mobile-swipe-row')
    expect(coffee).not.toHaveTextContent('未指定')
  })

  it('marks rows generated by a recurring rule', async () => {
    const { user } = renderList()
    await user.click(screen.getByRole('button', { name: /10\/02/ }))
    const phone = screen.getByText('中華電信').closest('.mobile-swipe-row')
    expect(within(phone).getByLabelText('定期支出')).toBeInTheDocument()
    const lunch = screen.getByText('午餐').closest('.mobile-swipe-row')
    expect(within(lunch).queryByLabelText('定期支出')).not.toBeInTheDocument()
  })

  it('expands only today by default', () => {
    renderList()
    expect(screen.getByRole('button', { name: /今天/ })).toHaveAttribute('aria-expanded', 'true')
    expect(screen.getByRole('button', { name: /10\/02/ })).toHaveAttribute('aria-expanded', 'false')
    expect(screen.getByText('午餐')).toBeInTheDocument()
    expect(screen.queryByText('中華電信')).not.toBeInTheDocument()
  })

  it('toggles a day open and closed from its heading', async () => {
    const { user } = renderList()
    const older = screen.getByRole('button', { name: /10\/02/ })
    await user.click(older)
    expect(older).toHaveAttribute('aria-expanded', 'true')
    expect(screen.getByText('中華電信')).toBeInTheDocument()
    const today = screen.getByRole('button', { name: /今天/ })
    await user.click(today)
    expect(today).toHaveAttribute('aria-expanded', 'false')
    expect(screen.queryByText('午餐')).not.toBeInTheDocument()
  })

  it('collapses every day when there is nothing today', () => {
    renderList({ today: '2026-10-06' })
    const headings = screen.getAllByTestId('expense-day-heading')
    expect(headings.every((el) => el.getAttribute('aria-expanded') === 'false')).toBe(true)
  })

  it('leaves upcoming charges out of the day list', () => {
    renderList()
    expect(screen.queryByText('房租')).not.toBeInTheDocument()
    expect(screen.queryByRole('button', { name: /本月預計/ })).not.toBeInTheDocument()
  })

  it('shows the empty state when only upcoming charges remain', () => {
    renderList({ rows: rows.filter((item) => item.isUpcoming) })
    expect(screen.getByText('沒有支出')).toBeInTheDocument()
  })

  it('shows the empty state when there are no rows', () => {
    renderList({ rows: [] })
    expect(screen.getByText('沒有支出')).toBeInTheDocument()
  })

  it('reveals each row\'s actions on swipe', () => {
    const { getActions } = renderList()
    expect(getActions).toHaveBeenCalledWith(expect.objectContaining({ name: '午餐' }))
    const surface = screen.getByText('午餐').closest('.swipe-actions-content')
    fireEvent.pointerDown(surface, { clientX: 300, clientY: 20, pointerId: 1 })
    fireEvent.pointerMove(surface, { clientX: 260, clientY: 20, pointerId: 1 })
    fireEvent.pointerMove(surface, { clientX: 150, clientY: 20, pointerId: 1 })
    fireEvent.pointerUp(surface, { clientX: 150, clientY: 20, pointerId: 1 })
    expect(screen.getByRole('button', { name: '編輯 午餐' })).toBeInTheDocument()
  })
})

describe('<UpcomingExpenseList />', () => {
  const renderUpcoming = (props = {}) => {
    const getActions = vi.fn(() => [])
    render(<UpcomingExpenseList rows={rows} getActions={getActions} {...props} />)
    return { user: userEvent.setup() }
  }

  it('starts collapsed with the count and total', () => {
    renderUpcoming()
    const toggle = screen.getByRole('button', { name: '本月預計 2 筆 · $19,488' })
    expect(toggle).toHaveTextContent('本月預計2 筆$19,488')
    expect(toggle).toHaveAttribute('aria-expanded', 'false')
    expect(screen.queryByText('房租')).not.toBeInTheDocument()
  })

  it('expands to the upcoming charges, soonest first, each with its date', async () => {
    const { user } = renderUpcoming()
    const toggle = screen.getByRole('button', { name: /本月預計/ })
    await user.click(toggle)
    expect(toggle).toHaveAttribute('aria-expanded', 'true')
    const names = screen.getAllByText(/房租|World gym/).map((el) => el.textContent)
    expect(names).toEqual(['房租', 'World gym'])
    expect(screen.getByText('房租').closest('.mobile-swipe-row')).toHaveTextContent('10/20 · 房屋 · Po')
    expect(screen.queryByText('午餐')).not.toBeInTheDocument()
  })

  it('renders nothing when nothing is upcoming', () => {
    const { container } = render(
      <UpcomingExpenseList rows={rows.filter((item) => !item.isUpcoming)} getActions={() => []} />,
    )
    expect(container).toBeEmptyDOMElement()
  })

  it('takes a label', () => {
    render(<UpcomingExpenseList rows={rows} getActions={() => []} label="本期預計" />)
    expect(screen.getByRole('button', { name: /本期預計 2 筆/ })).toBeInTheDocument()
  })

  it('stacks one tile per distinct category of the upcoming charges', () => {
    const { container } = render(<UpcomingExpenseList rows={rows} getActions={() => []} />)
    const stack = container.querySelector('.expense-upcoming-stack')
    expect(stack).toHaveAttribute('aria-hidden', 'true')
    const upcomingCategories = new Set(
      rows.filter((row) => row.isUpcoming).map((row) => `${row.categoryName}|${row.categoryIcon}`),
    )
    expect(stack.querySelectorAll('.category-icon')).toHaveLength(upcomingCategories.size)
  })

  it('hides the tile stack while open', async () => {
    const user = userEvent.setup()
    const { container } = render(<UpcomingExpenseList rows={rows} getActions={() => []} />)
    await user.click(screen.getByRole('button', { name: /本月預計/ }))
    expect(container.querySelector('.expense-upcoming-stack')).toBeNull()
  })
})

describe('<ExpenseDayList expandAll />', () => {
  it('expands every day', () => {
    render(
      <ExpenseDayList rows={rows} today="2026-10-04" getActions={() => []} expandAll />,
    )
    expect(
      screen.getAllByTestId('expense-day-heading').every((el) => el.getAttribute('aria-expanded') === 'true'),
    ).toBe(true)
  })
})

describe('<ExpenseDayStrip />', () => {
  const renderStrip = (props = {}) => {
    render(
      <ExpenseDayStrip
        rows={rows}
        month="2026-10"
        today="2026-10-04"
        getActions={() => []}
        empty={<div>沒有支出</div>}
        {...props}
      />,
    )
    return userEvent.setup()
  }

  it('offers every day of the month up to today, opening on today', () => {
    renderStrip()
    const days = within(screen.getByRole('group', { name: '選擇日期' })).getAllByRole('button')
    expect(days).toHaveLength(4)
    expect(screen.getByRole('button', { name: '今天 · 10/04（日），$200' })).toHaveAttribute('aria-pressed', 'true')
    expect(screen.getByRole('button', { name: '昨天 · 10/03（六），沒有支出' })).toHaveAttribute('aria-pressed', 'false')
    expect(screen.getByTestId('expense-day-heading')).toHaveTextContent('今天 · 10/04（日）$200')
    expect(screen.getByText('午餐')).toBeInTheDocument()
    expect(screen.queryByText('中華電信')).not.toBeInTheDocument()
  })

  it('switches the list to the picked day', async () => {
    const user = renderStrip()
    await user.click(screen.getByRole('button', { name: /^10\/02/ }))
    expect(screen.getByTestId('expense-day-heading')).toHaveTextContent('10/02（五）$999')
    expect(screen.getByText('中華電信')).toBeInTheDocument()
    expect(screen.queryByText('午餐')).not.toBeInTheDocument()
  })

  it('says so when the picked day has no spending', async () => {
    const user = renderStrip()
    await user.click(screen.getByRole('button', { name: /10\/03/ }))
    expect(screen.getByText('這天沒有支出')).toBeInTheDocument()
  })

  it('opens on an empty today with a prompt', () => {
    renderStrip({ today: '2026-10-06' })
    expect(screen.getByText('今天還沒有支出')).toBeInTheDocument()
  })

  it('leaves upcoming charges out', () => {
    renderStrip()
    expect(screen.queryByText('房租')).not.toBeInTheDocument()
  })

  it('shows the empty state when the month has no charged rows', () => {
    renderStrip({ rows: rows.filter((item) => item.isUpcoming) })
    expect(screen.getByText('沒有支出')).toBeInTheDocument()
  })
})
